providers:
  docker:
    exposedByDefault: false

  file:
    directory: "/etc/traefik/conf"
    # filename: "/etc/traefik/conf/tls.yml"
    watch: true

api:
  insecure: true

entrypoints:
  web:
    address: ":80"
  admin:
    address: ":3000"
  websecure:
    address: ":443"
